// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use env vars when available; fall back to known dev values to avoid blank screen during setup
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) || "https://onidwnrytkrxsjkuoxws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uaWR3bnJ5dGtyeHNqa3VveHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjM0MjMsImV4cCI6MjA2OTc5OTQyM30.G6aUfJZgAuK__KQLP66DmSNYZAdaHp0CRzcW1tHP0cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);